# Generated by Django 3.2.9 on 2022-01-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardvideo',
            options={'ordering': ('-created_at',)},
        ),
    ]
