# Generated by Django 3.2.6 on 2021-11-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_mentormenteerelations_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=999, null=True),
        ),
        migrations.AlterField(
            model_name='mentormenteerelations',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=999, null=True),
        ),
        migrations.AlterField(
            model_name='mentorpaymentplans',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='total_money_earned',
            field=models.CharField(blank=True, default=0, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='mentorrequest',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=999, null=True),
        ),
        migrations.AlterField(
            model_name='mentorskill',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mentorprofile'),
        ),
    ]
