# Generated by Django 3.2.9 on 2021-11-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211114_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_tags',
            field=models.ManyToManyField(blank=True, null=True, to='users.Skill'),
        ),
    ]
