# Generated by Django 3.2.9 on 2021-11-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211112_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteeprofile',
            name='image',
            field=models.ImageField(blank=True, default='https://findamentorapp.s3.amazonaws.com/profile_pics/default.png', null=True, upload_to='profile_pics/mentee'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='image',
            field=models.ImageField(blank=True, default='https://findamentorapp.s3.amazonaws.com/profile_pics/default.png', null=True, upload_to='profile_pics/mentor'),
        ),
    ]
