# Generated by Django 3.2.9 on 2021-11-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_content_content_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteeinterest',
            name='interest',
            field=models.ManyToManyField(blank=True, null=True, to='users.Skill'),
        ),
        migrations.RemoveField(
            model_name='mentorskill',
            name='skill',
        ),
        migrations.AddField(
            model_name='mentorskill',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, to='users.Skill'),
        ),
    ]
