# Generated by Django 3.2.6 on 2021-11-11 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_coursecatergory_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecatergory',
            name='content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.content'),
        ),
        migrations.AlterField(
            model_name='coursecatergory',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.skill'),
        ),
    ]
