# Generated by Django 3.2.9 on 2021-11-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211112_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_new_message',
            field=models.BooleanField(default=False),
        ),
    ]
