# Generated by Django 3.2.6 on 2021-11-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211111_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menteeinterest',
            name='interest',
        ),
        migrations.AddField(
            model_name='menteeinterest',
            name='interest',
            field=models.ManyToManyField(to='users.Catergory'),
        ),
    ]
