# Generated by Django 3.2.9 on 2021-11-17 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_mentorrequesttime_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorrequesttime',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='mentorrequesttime',
            name='from_hour',
        ),
        migrations.RemoveField(
            model_name='mentorrequesttime',
            name='from_weekday',
        ),
        migrations.RemoveField(
            model_name='mentorrequesttime',
            name='to_date',
        ),
        migrations.RemoveField(
            model_name='mentorrequesttime',
            name='to_hour',
        ),
        migrations.RemoveField(
            model_name='mentorrequesttime',
            name='to_weekday',
        ),
        migrations.RemoveField(
            model_name='mentorrequesttime',
            name='total_hours',
        ),
        migrations.AddField(
            model_name='mentorrequesttime',
            name='mentor_availibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.mentoravailability'),
        ),
    ]
