# Generated by Django 3.2.9 on 2021-11-18 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211117_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='mentorrequest',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='mentorrequesttime',
            options={'ordering': ('-created_at',)},
        ),
    ]
