# Generated by Django 3.2.6 on 2021-11-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_mentorrequest_declined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteeprofile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pics/mentee'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pics/mentor'),
        ),
    ]
