# Generated by Django 3.2.9 on 2021-11-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211113_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentoravailability',
            options={'ordering': ('weekday',)},
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='total_hours_teached',
            field=models.CharField(blank=True, default=0, max_length=120, null=True),
        ),
    ]
