# Generated by Django 3.2.9 on 2021-11-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211113_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorrequesttime',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=999, null=True),
        ),
    ]
