# Generated by Django 3.2.9 on 2021-11-12 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211111_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentormenteerelations',
            name='mentee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentee_relation', to='users.menteeprofile'),
        ),
        migrations.AlterField(
            model_name='mentormenteerelations',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_relation', to='users.mentorprofile'),
        ),
    ]
