# Generated by Django 3.2.9 on 2021-11-19 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_mentorrequesttimeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorBookedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('weekday', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, null=True)),
                ('is_available_status', models.BooleanField(default=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_books', to='users.mentorprofile')),
                ('mentor_time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mentorrequesttimeslot')),
            ],
        ),
    ]
