# Generated by Django 3.2.9 on 2021-11-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_mentorrequesttime_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorrequesttime',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True),
        ),
    ]
