# Generated by Django 3.2.9 on 2021-11-20 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_mentorbookedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorbookedevent',
            name='mentee_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.mentorrequest'),
        ),
    ]
