# Generated by Django 3.2.9 on 2021-11-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
