# Generated by Django 3.2.9 on 2021-11-13 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0003_auto_20211112_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
