# Generated by Django 3.2.9 on 2021-11-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0006_auto_20211113_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
