# Generated by Django 3.2.9 on 2021-11-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0008_room_is_new_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_new_message',
            field=models.BooleanField(default=True),
        ),
    ]
