# Generated by Django 3.2.9 on 2021-11-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0009_alter_room_is_new_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='first_user',
            new_name='mentee',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='second_user',
            new_name='mentor',
        ),
    ]
