# Generated by Django 3.2.9 on 2021-11-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0010_auto_20211113_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='mentee_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='menter_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
