# Generated by Django 3.2.9 on 2021-11-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20211117_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
