# Generated by Django 3.2.9 on 2021-11-18 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_meeting_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ('-created_at',)},
        ),
    ]
