# Generated by Django 3.2.9 on 2021-11-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_auto_20211122_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrecording',
            name='stopresponse',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
