# Generated by Django 3.2.9 on 2021-11-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_meetingrecording_stopresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_url',
            field=models.URLField(blank=True, default='#', null=True),
        ),
    ]
