# Generated by Django 3.2.9 on 2022-01-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_meeting_meeting_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrecording',
            name='recording',
            field=models.FileField(blank=True, null=True, upload_to='recording/'),
        ),
    ]
