# Generated by Django 3.2 on 2022-01-12 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting', '0010_meetingrecording_recording'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingrecording',
            name='content',
        ),
        migrations.RemoveField(
            model_name='meetingrecording',
            name='recording_url',
        ),
        migrations.AlterField(
            model_name='meetingrecording',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_meeting_recording', to=settings.AUTH_USER_MODEL),
        ),
    ]
